name: Apply PWA Patch
on:
  workflow_dispatch:
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create branch
        run: |
          git checkout -b feat/pwa-and-tests
          printf "%s" "$PR_DIFF" > pr.diff
          git apply pr.diff
        env:
          PR_DIFF: |
            # <-- paste the pr.diff content I gave you here (exactly) -->
      - name: Install & test
        run: |
          npm ci
          npm run build
          npm test
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feat/pwa-and-tests
          title: "feat(pwa): PWA + Tests + CI"
          body: "Adds manifest, Workbox SW (injectManifest), install/update UX, unit tests, and CI (Lighthouse)."
          base: main
